/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TelasInternas;

import Controllers.Consultas;
import Controllers.Pacientes;
import Modulos.IdAutomatico;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author tung tung tung sahur
 */
public class InternacoesAdministracao extends javax.swing.JInternalFrame {

    private static final String FILE_PATH_MEDICOS = "data/medicos.csv";
    private static final String FILE_PATH_PLANOS = "data/planosDeSaude.csv";
    private static final String FILE_PATH_PACIENTES = "data/pacientes.csv";
    private static final String FILE_PATH_SALAS = "data/salasInternacao.csv";
    private static final String FILE_PATH_INTERNACOES = "data/internacoes.csv";


    private Integer id = -1;
    private String nomeUsuario;

    /**
     * Creates new form AgendamentoConsultas
     */
    public InternacoesAdministracao() {
        initComponents();
        tabelaInternacoes.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        excluirInternacao = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaInternacoes = new javax.swing.JTable();
        finalizarInternacao = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setText("Administração das Internações");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel5.setText("Tabela Internações");

        excluirInternacao.setBackground(new java.awt.Color(204, 204, 204));
        excluirInternacao.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        excluirInternacao.setText("Cancelar Internação");
        excluirInternacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        excluirInternacao.setContentAreaFilled(false);
        excluirInternacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirInternacaoMouseClicked(evt);
            }
        });

        tabelaInternacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome do Médico", "Nome do Paciente", "Horario da Internação", "Sala da Internação", "Situação", "Custo da Internação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInternacoes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaInternacoesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelaInternacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInternacoesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaInternacoes);
        if (tabelaInternacoes.getColumnModel().getColumnCount() > 0) {
            tabelaInternacoes.getColumnModel().getColumn(0).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(1).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(2).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(3).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(4).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(5).setResizable(false);
            tabelaInternacoes.getColumnModel().getColumn(6).setResizable(false);
        }

        finalizarInternacao.setBackground(new java.awt.Color(204, 204, 204));
        finalizarInternacao.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        finalizarInternacao.setText("Finalizar Internação");
        finalizarInternacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        finalizarInternacao.setContentAreaFilled(false);
        finalizarInternacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizarInternacaoMouseClicked(evt);
            }
        });
        finalizarInternacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarInternacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(finalizarInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(excluirInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jLabel1)))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizarInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirInternacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirInternacaoMouseClicked
        if(id == -1){
            JOptionPane.showMessageDialog(null, "É necessário que você selecione alguma internação!");
            return;
        }

        List<String> linhasInternacoes = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_INTERNACOES))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");
                int idAtual = Integer.parseInt(data[0]);

                if (id != idAtual) {
                    linhasInternacoes.add(linha);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH_INTERNACOES))) {
            for (String l : linhasInternacoes) {
                writer.write(l);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "Internação removida com sucesso!");

        this.setNulo();
        this.reiniciarTabela();
    }//GEN-LAST:event_excluirInternacaoMouseClicked

    private void finalizarInternacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizarInternacaoMouseClicked
        if(id == -1){
            JOptionPane.showMessageDialog(null, "É necessário que você selecione alguma internação para conseguir finalizar!");
            return;
        }

        List<String> linhas = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_INTERNACOES))) {
            String linha;

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");
                if(Integer.parseInt(data[0]) == id) {
                    data[5] = "Finalizada";

                    linha = String.join(",", data);
                }
                linhas.add(linha);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Houve algum erro na edição da consulta!");
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH_INTERNACOES))) {
            for (String l : linhas) {
                writer.write(l);
                writer.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar alterações no CSV!");
        }

        JOptionPane.showMessageDialog(null, "Internação finalizada com sucesso!");

        String linhaHorario = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yy/MM/dd-HH:mm"));

        this.salvarInternacao(linhaHorario);

        this.setNulo();
        this.reiniciarTabela();
    }//GEN-LAST:event_finalizarInternacaoMouseClicked

    private void tabelaInternacoesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaInternacoesAncestorAdded
        DefaultTableModel modelTabela = (DefaultTableModel) tabelaInternacoes.getModel();
        modelTabela.setNumRows(0);

        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_INTERNACOES))) {
            String linha;

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");

                if(Objects.equals(data[5], "internado")) {
                    Object[] dados = { data[0], retornaNomeMedico(Integer.parseInt(data[2])), retornaNomePaciente(Integer.parseInt(data[1])), data[3], data[4], data[5], Double.parseDouble(data[6])};
                    modelTabela.addRow(dados);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Houve algum erro na criação automática da lista de internações");
        }
    }//GEN-LAST:event_tabelaInternacoesAncestorAdded

    private void tabelaInternacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInternacoesMouseClicked
        id = Integer.parseInt(tabelaInternacoes.getValueAt(tabelaInternacoes.getSelectedRow(), 0).toString());
        nomeUsuario = tabelaInternacoes.getValueAt(tabelaInternacoes.getSelectedRow(), 2).toString();
    }//GEN-LAST:event_tabelaInternacoesMouseClicked

    private void finalizarInternacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarInternacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizarInternacaoActionPerformed

    // retorna o nome do paciente baseado no id enviado, funcionando como se fosse um inner join no mysql
    private String retornaNomePaciente(int idPaciente) {
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_PACIENTES))) {
            String linha;

            if((linha = reader.readLine()) == null) {
                return null;
            } else {
                String[] data = linha.split(",");
                if(idPaciente == Integer.parseInt(data[0])) {
                    return data[1];
                }
            }

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");
                if(idPaciente == Integer.parseInt(data[0])) {
                    return data[1];
                }
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Houve algum erro na listagem automática dos IDs");
        }

        return null;
    }

    // retorna o nome do médico baseado no id enviado, funcionando como se fosse um inner join no mysql
    private String retornaNomeMedico(int idMedico) {
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_MEDICOS))) {
            String linha;

            if((linha = reader.readLine()) == null) {
                return null;
            } else {
                String[] data = linha.split(",");
                if(idMedico == Integer.parseInt(data[0])) {
                    return data[1];
                }
            }

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");
                if(idMedico == Integer.parseInt(data[0])) {
                    return data[1];
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Houve algum erro na listagem automática dos IDs");
        }
        return null;
    }

    private void reiniciarTabela() {
        DefaultTableModel modelTabela = (DefaultTableModel) tabelaInternacoes.getModel();
        modelTabela.setNumRows(0);

        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_INTERNACOES))) {
            String linha;

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");

                if(Objects.equals(data[5], "internado")) {
                    Object[] dados = { data[0], retornaNomeMedico(Integer.parseInt(data[2])), retornaNomePaciente(Integer.parseInt(data[1])), data[3], data[4], data[5], Double.parseDouble(data[6])};
                    modelTabela.addRow(dados);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Houve algum erro na criação automática da lista de internações!");
        }
    }

    //Salva a hora de saída da internação no csv internação.
    private void salvarInternacao(String horarioSaida) {
        List<String> linhas = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH_INTERNACOES))) {
            String linha;

            while ((linha = reader.readLine()) != null) {
                String[] data = linha.split(",");

                String nomeAtual = retornaNomePaciente(Integer.parseInt(data[1]));

                if (Objects.equals(nomeAtual, nomeUsuario)) {
                    linha += "," + horarioSaida;
                }
                linhas.add(linha);
            }

        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH_INTERNACOES))) {
            for (String l : linhas) {
                writer.write(l);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void setNulo() {
        id = -1;
        nomeUsuario = null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirInternacao;
    private javax.swing.JButton finalizarInternacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelaInternacoes;
    // End of variables declaration//GEN-END:variables
}
